blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns=[
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^author/(?P<pk>[0-9]+)/$', views.AuthorDetailView.as_view(), name='author_detail')
]

sandbox/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace="blog"))
]

blog/models.py
from django.db import models

# Create your models here.

class Author(models.Model):

    name = models.CharField(max_length=200)
    join_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def list_of_articles(self):
        return self.objects.all()

class Article(models.Model):

    article_author = models.ForeignKey(Author, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    content = models.CharField(max_length=2000)
    publication_date = models.DateTimeField(auto_now_add=True)
    last_modification_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Comment(models.Model):

    article = models.ForeignKey(Article, null=True, on_delete=models.SET_NULL)
    comment_author = models.ForeignKey(Author,null=True, on_delete=models.SET_NULL)
    content = models.CharField(max_length=300)
    publication_date = models.DateTimeField(auto_now_add=True)
    last_modification_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "Comment to " + self.article.title + " by " + self.comment_author.name

blog/views.py
from django.views import generic
from .models import *

class IndexView(generic.ListView):

    template_name = 'blog/IndexView.html'

    def get_queryset(self):
        return Article.objects.all()

class DetailView(generic.DetailView):

    template_name = 'blog/DetailView.html'
    model = Article

class AuthorDetailView(generic.DetailView):

    template_name = 'blog/AuthorDetailView.html'
    model = Author

blog/templates/blog/AuthorDetailView.html
<h1 align="center">{{author.name}}</h1>
<br>
<br>
<br>
<br>
Author of following articles:
<ul>
    {% for article in author.article_set.all %}
    <li><a href="{% url 'blog:detail' article.id %}">{{article.title}}</a></li>
    {% endfor %}
</ul>
<br>
<br>
<br>
<br>
<p><a href="{% url 'blog:index' %}">Return to main page</a></p>

blog/templates/blog/DetailView.html
<h1 align="center">{{article.title}}</h1>

<p>{{article.content}}</p>

<p align="right">Author: <a href="{% url 'blog:author_detail' article.article_author.id %}">{{article.article_author}}</a></p>
<p align="right">Publicated: {{article.publication_date}}</p>
{% if article.publication_date != article.last_modification_date  %}
<p align="right">{{article.article_author}}</p>
{% endif %}


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{% for comment in article.comment_set.all %}
<p align="center">{{comment.content}}</p>
<p align="right">{{comment.comment_author}}</p>
<p align="right">{{comment.publication_date}}</p>
{% endfor %}
<br>
<br>
<br>
<br>
<p><a href="{% url 'blog:index' %}">Return to main page</a></p>

blog/templates/blog/IndexVIew.html
<h1 align="center">Index page</h1>

{% for article in article_list  %}
<p align="center">{{article.title}}</p>
<p align="center">{{article.content|truncatewords:30}} <a href="{% url 'blog:detail' article.id %}">Read more</a></p>
{% endfor %}